### ISSUE TITLE
No lib folder in 1.8.0

### ISSUE THREAD

**Issue by tagshch** [demskie/netparser#19]
Steps to reproduce (+ diff between 1.7.0 and 1.8.0):

https://user-images.githubusercontent.com/4018124/128692560-02798e88-74f4-44b6-a581-c79702fddac9.mov

**Comment by demskie** [comment]
Oh my goodness, I'm so sorry. This has been fixed in version 1.8.1 and I've deprecated version 1.8.0.

**Comment by tagshch** [comment]
Thank you)
