### ISSUE TITLE
summarize not working correctly

### ISSUE THREAD

**Issue by giladfapri** [demskie/netparser#6]
summarize([77.138.225.244/32,77.138.225.245]) will result: [77.138.225.244/31], when clearly that isn't right

**Comment by astellingwerf** [comment]
Can you explain why you closed the issue? I seem to notice the same behavior.
My understanding of summarize is that it would condense adjacent addresses or CIDrs into bigger CIDRs, without including addresses that weren't part of the input.

**Comment by demskie** [comment]
@astellingwerf can you provide some input that reproduces the issue?

Note that in his example the second address has an implied /32 that makes the output valid.

I can see a potential issue with assuming a network address is /32 if a CIDR is not present. Maybe a better behavior would be to take Classful Addressing into account to assume the correct mask length.

**Comment by astellingwerf** [comment]
The primary issue that I saw is that the function internally generates invalid Networks, which then causes invalid decisions to be made, and therefor with unexpected results.

The last paragraph of RFC 4632 says:
```
   x is a 1- to 7-bit value, based on the prefix length, shifted into
   the most significant bits of the octet and converted into decimal
   form; the least significant bits of the octet are zero.
```
It means that for example a /31 must end with an even number, and a /30 ends in a number divisible by 4.

**Comment by demskie** [comment]
merged and fixed: https://github.com/demskie/netparser/pull/17
